In [2]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from model.analyze import analyze_variables
from model.train import (
    cross_validation,
    grid_report,
    load_data,
    random_seed,
)
from model.model import save_model
import random

random.seed(random_seed)

In [3]:
train_dataset, test_dataset = load_data("../data/raw_data.csv")
experiment = "adaboost"
case_folder = f"./reports/{experiment}"


def model_path(output_folder: str):
    return f"{output_folder}/model"

In [4]:
output_folder = f"{case_folder}/trees_simple"
grid, summary = cross_validation(
    [("model", AdaBoostClassifier())],
    train_dataset,
    {
        "model__n_estimators": [50, 100, 200],
        "model__learning_rate": [0.1, 0.5, 1],
    },
    include_all=False,
    include_bias=False,
)
summary

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__learning_rate,param_model__n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
7,4.008861,0.392539,0.321879,0.041323,1.0,100,"{'model__learning_rate': 1, 'model__n_estimato...",0.900188,0.879537,0.888646,0.892399,0.892712,0.890696,0.006720,1
8,7.173552,0.280469,0.393333,0.120648,1.0,200,"{'model__learning_rate': 1, 'model__n_estimato...",0.899875,0.879537,0.888333,0.888646,0.893025,0.889883,0.006644,2
4,4.026486,0.534916,0.332377,0.053985,0.5,100,"{'model__learning_rate': 0.5, 'model__n_estima...",0.895181,0.881101,0.886769,0.890522,0.892712,0.889257,0.004926,3
6,1.798839,0.373337,0.168108,0.054886,1.0,50,"{'model__learning_rate': 1, 'model__n_estimato...",0.900188,0.879537,0.886769,0.888020,0.889584,0.888820,0.006646,4
5,7.963713,0.730829,0.468003,0.117717,0.5,200,"{'model__learning_rate': 0.5, 'model__n_estima...",0.895494,0.879537,0.884892,0.886769,0.888333,0.887005,0.005179,5

In [5]:
model = grid_report(grid, test_dataset, experiment)
save_model(model, model_path(output_folder))
analyze_variables(model, test_dataset, output_folder)

{'model__learning_rate': 1, 'model__n_estimators': 100}
              precision    recall  f1-score   support

           0     0.9348    0.9612    0.9478      5742
           1     0.9415    0.9031    0.9219      3974

    accuracy                         0.9374      9716
   macro avg     0.9381    0.9321    0.9349      9716
weighted avg     0.9375    0.9374    0.9372      9716

2025/02/26 07:43:36 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

In [3]:
output_folder = f"{case_folder}/trees_unbiased"
grid, summary = cross_validation(
    [("model", AdaBoostClassifier())],
    train_dataset,
    {
        "model__n_estimators": [50, 100, 200],
        "model__learning_rate": [0.1, 0.5, 1],
    },
    include_all=True,
    include_bias=False,
)
summary

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__learning_rate,param_model__n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
8,14.278301,0.899763,0.595193,0.352501,1.0,200,"{'model__learning_rate': 1, 'model__n_estimato...",0.908323,0.886108,0.894901,0.900219,0.897091,0.897328,0.007226,1
7,10.283711,0.238389,0.627765,0.065265,1.0,100,"{'model__learning_rate': 1, 'model__n_estimato...",0.906758,0.882666,0.892399,0.898655,0.894589,0.895013,0.007883,2
5,31.004837,0.826648,1.176691,0.178004,0.5,200,"{'model__learning_rate': 0.5, 'model__n_estima...",0.900501,0.881727,0.890835,0.891774,0.893650,0.891697,0.006024,3
6,4.550140,0.616067,0.327318,0.057695,1.0,50,"{'model__learning_rate': 1, 'model__n_estimato...",0.900814,0.883917,0.886456,0.894589,0.890835,0.891322,0.005992,4
4,17.164481,1.402539,1.033944,0.145083,0.5,100,"{'model__learning_rate': 0.5, 'model__n_estima...",0.897372,0.877660,0.883954,0.891148,0.888958,0.887818,0.006660,5

In [4]:
model = grid_report(grid, test_dataset, experiment)
save_model(model, model_path(output_folder))
analyze_variables(model, test_dataset, output_folder)

{'model__learning_rate': 1, 'model__n_estimators': 200}
              precision    recall  f1-score   support

           0     0.9387    0.9702    0.9542      5742
           1     0.9548    0.9084    0.9310      3974

    accuracy                         0.9449      9716
   macro avg     0.9467    0.9393    0.9426      9716
weighted avg     0.9453    0.9449    0.9447      9716

2025/02/25 21:50:41 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

In [3]:
output_folder = f"{case_folder}/trees"
grid, summary = cross_validation(
    [("model", AdaBoostClassifier())],
    train_dataset,
    {
        "model__n_estimators": [50, 100, 200],
        "model__learning_rate": [0.1, 0.5, 1],
    },
    include_all=True,
    include_bias=True,
)
summary

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__learning_rate,param_model__n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
8,13.550304,0.999846,0.635572,0.182235,1.0,200,"{'model__learning_rate': 1, 'model__n_estimato...",0.974030,0.971527,0.974351,0.975602,0.974977,0.974097,0.001394,1
7,7.682385,1.042080,0.587492,0.126963,1.0,100,"{'model__learning_rate': 1, 'model__n_estimato...",0.974030,0.971214,0.974038,0.975602,0.974977,0.973972,0.001502,2
5,15.907184,1.810849,1.055251,0.094212,0.5,200,"{'model__learning_rate': 0.5, 'model__n_estima...",0.970588,0.970275,0.974664,0.975602,0.974977,0.973221,0.002300,3
6,4.443999,0.314834,0.364120,0.070874,1.0,50,"{'model__learning_rate': 1, 'model__n_estimato...",0.972466,0.969962,0.971849,0.973725,0.973100,0.972220,0.001291,4
4,8.623778,1.760614,0.594009,0.073019,0.5,100,"{'model__learning_rate': 0.5, 'model__n_estima...",0.967772,0.964330,0.969033,0.969972,0.968095,0.967841,0.001916,5

In [4]:
model = grid_report(grid, test_dataset, experiment)
save_model(model, model_path(output_folder))
analyze_variables(model, test_dataset, output_folder)

{'model__learning_rate': 1, 'model__n_estimators': 200}

2025/02/24 07:29:09 INFO mlflow.tracking.fluent: Experiment with name 'adaboost' does not exist. Creating a new experiment.

              precision    recall  f1-score   support

           0     0.9847    0.9958    0.9902      5742
           1     0.9939    0.9776    0.9857      3974

    accuracy                         0.9884      9716
   macro avg     0.9893    0.9867    0.9879      9716
weighted avg     0.9884    0.9884    0.9884      9716

2025/02/24 07:29:15 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

In [6]:
output_folder = f"{case_folder}/linear_simple"
grid, summary = cross_validation(
    [("model", AdaBoostClassifier())],
    train_dataset,
    {   
        "model__estimator": [LogisticRegression()],
        "model__n_estimators": [50, 100, 200],
        "model__learning_rate": [0.1, 0.5, 1],
    },
    include_all=False,
    include_bias=False,
)
summary

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__estimator,param_model__learning_rate,param_model__n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,3.899878,0.249070,0.121197,0.013277,LogisticRegression(),0.1,50,"{'model__estimator': LogisticRegression(), 'mo...",0.929287,0.919900,0.921802,0.923366,0.924617,0.923794,0.003167,1
4,5.616748,0.707496,0.175925,0.050285,LogisticRegression(),0.5,100,"{'model__estimator': LogisticRegression(), 'mo...",0.908010,0.894556,0.895840,0.899281,0.902409,0.900019,0.004846,2
5,5.286659,0.888017,0.111128,0.028971,LogisticRegression(),0.5,200,"{'model__estimator': LogisticRegression(), 'mo...",0.908010,0.894556,0.895840,0.899281,0.902409,0.900019,0.004846,2
2,9.404139,1.665389,0.236172,0.052371,LogisticRegression(),0.1,200,"{'model__estimator': LogisticRegression(), 'mo...",0.905194,0.893304,0.897717,0.901470,0.898342,0.899205,0.003969,4
1,7.517932,0.131651,0.202146,0.043202,LogisticRegression(),0.1,100,"{'model__estimator': LogisticRegression(), 'mo...",0.904881,0.892365,0.897717,0.901470,0.898342,0.898955,0.004166,5

In [7]:
model = grid_report(grid, test_dataset, experiment)
save_model(model, model_path(output_folder))
analyze_variables(model, test_dataset, output_folder)

{'model__estimator': LogisticRegression(), 'model__learning_rate': 0.1, 'model__n_estimators': 50}
              precision    recall  f1-score   support

           0     0.9482    0.8932    0.9199      5742
           1     0.8577    0.9295    0.8922      3974

    accuracy                         0.9081      9716
   macro avg     0.9030    0.9114    0.9060      9716
weighted avg     0.9112    0.9081    0.9086      9716

2025/02/26 07:45:22 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

In [5]:
output_folder = f"{case_folder}/linear_unbiased"
grid, summary = cross_validation(
    [("model", AdaBoostClassifier())],
    train_dataset,
    {   
        "model__estimator": [LogisticRegression()],
        "model__n_estimators": [50, 100, 200],
        "model__learning_rate": [0.1, 0.5, 1],
    },
    include_all=True,
    include_bias=False,
)
summary

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__estimator,param_model__learning_rate,param_model__n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
2,24.699338,1.229267,0.495074,0.058525,LogisticRegression(),0.1,200,"{'model__estimator': LogisticRegression(), 'mo...",0.932103,0.925845,0.928370,0.928996,0.927432,0.928549,0.002070,1
1,15.254272,1.112035,0.383877,0.073212,LogisticRegression(),0.1,100,"{'model__estimator': LogisticRegression(), 'mo...",0.930538,0.925219,0.927432,0.926806,0.927119,0.927423,0.001734,2
7,5.534522,2.252741,0.191076,0.024786,LogisticRegression(),1.0,100,"{'model__estimator': LogisticRegression(), 'mo...",0.923967,0.916771,0.928058,0.927432,0.927119,0.924669,0.004195,3
8,5.021694,1.685710,0.203106,0.078382,LogisticRegression(),1.0,200,"{'model__estimator': LogisticRegression(), 'mo...",0.923967,0.916771,0.928058,0.927432,0.927119,0.924669,0.004195,3
6,5.132027,1.514979,0.221935,0.020149,LogisticRegression(),1.0,50,"{'model__estimator': LogisticRegression(), 'mo...",0.923967,0.916771,0.928058,0.925555,0.928058,0.924482,0.004158,5

In [6]:
model = grid_report(grid, test_dataset, experiment)
save_model(model, model_path(output_folder))
analyze_variables(model, test_dataset, output_folder)

{'model__estimator': LogisticRegression(), 'model__learning_rate': 0.1, 'model__n_estimators': 200}
              precision    recall  f1-score   support

           0     0.9510    0.9427    0.9468      5742
           1     0.9182    0.9298    0.9240      3974

    accuracy                         0.9374      9716
   macro avg     0.9346    0.9362    0.9354      9716
weighted avg     0.9376    0.9374    0.9375      9716

2025/02/25 21:53:07 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

In [5]:
output_folder = f"{case_folder}/linear"
grid, summary = cross_validation(
    [("model", AdaBoostClassifier())],
    train_dataset,
    {   
        "model__estimator": [LogisticRegression()],
        "model__n_estimators": [50, 100, 200],
        "model__learning_rate": [0.1, 0.5, 1],
    },
    include_all=True,
    include_bias=True,
)
summary

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__estimator,param_model__learning_rate,param_model__n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
2,30.748541,0.942519,0.804284,0.040110,LogisticRegression(),0.1,200,"{'model__estimator': LogisticRegression(), 'mo...",0.973091,0.969962,0.973413,0.973725,0.974977,0.973034,0.001663,1
1,16.384019,1.280989,0.411680,0.055486,LogisticRegression(),0.1,100,"{'model__estimator': LogisticRegression(), 'mo...",0.972153,0.968398,0.973100,0.973413,0.974664,0.972345,0.002131,2
7,7.482768,2.074852,0.298618,0.042821,LogisticRegression(),1.0,100,"{'model__estimator': LogisticRegression(), 'mo...",0.969962,0.967459,0.974351,0.973725,0.974977,0.972095,0.002901,3
8,6.609331,0.802348,0.221576,0.087299,LogisticRegression(),1.0,200,"{'model__estimator': LogisticRegression(), 'mo...",0.969962,0.967459,0.974351,0.973725,0.974977,0.972095,0.002901,3
6,6.934848,1.163179,0.271670,0.047722,LogisticRegression(),1.0,50,"{'model__estimator': LogisticRegression(), 'mo...",0.969962,0.967459,0.974351,0.973725,0.974038,0.971907,0.002734,5

In [6]:
model = grid_report(grid, test_dataset, experiment)
save_model(model, model_path(output_folder))
analyze_variables(model, test_dataset, output_folder)

{'model__estimator': LogisticRegression(), 'model__learning_rate': 0.1, 'model__n_estimators': 200}
              precision    recall  f1-score   support

           0     0.9843    0.9906    0.9874      5742
           1     0.9863    0.9771    0.9817      3974

    accuracy                         0.9851      9716
   macro avg     0.9853    0.9838    0.9845      9716
weighted avg     0.9851    0.9851    0.9851      9716

2025/02/24 07:31:56 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.