In [1]:
%pip install ../model --q

Note: you may need to restart the kernel to use updated packages.

In [2]:
from sklearn.tree import DecisionTreeClassifier
from model.analyze import analyze_variables, check_bias, print_tree
from model.train import (
    cross_validation,
    grid_report,
    load_data,
    random_seed,
    test_report_umbral,
    train_unbiased_model,
)
from model.model import save_model
import random

random.seed(random_seed)

WARNING:root:No module named 'tensorflow': AdversarialDebiasing will be unavailable. To install, run:
pip install 'aif360[AdversarialDebiasing]'
WARNING:root:No module named 'tensorflow': AdversarialDebiasing will be unavailable. To install, run:
pip install 'aif360[AdversarialDebiasing]'
WARNING:root:No module named 'fairlearn': ExponentiatedGradientReduction will be unavailable. To install, run:
pip install 'aif360[Reductions]'
WARNING:root:No module named 'fairlearn': GridSearchReduction will be unavailable. To install, run:
pip install 'aif360[Reductions]'
WARNING:root:No module named 'inFairness': SenSeI and SenSR will be unavailable. To install, run:
pip install 'aif360[inFairness]'
WARNING:root:No module named 'fairlearn': GridSearchReduction will be unavailable. To install, run:
pip install 'aif360[Reductions]'

In [3]:
train_dataset, test_dataset = load_data("../data/raw_data.csv")
bias_prone_variables = ["Sexo", "Grupo Etario"]
experiment = "final"
case_folder = f"./reports/{experiment}"


def model_path(output_folder: str):
    return f"{output_folder}/model"

In [4]:
output_folder = f"{case_folder}/biased"
grid, summary = cross_validation(
    [("model", DecisionTreeClassifier())],
    train_dataset,
    {
        "model__splitter": ["random", "best"],
        "model__max_depth": [3, 5, 7],
        "model__min_samples_split": [2, 3, 4],
        "model__min_samples_leaf": [1, 2, 3],
    },
    include_all=True,
    include_bias=True,
)
summary

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__max_depth,param_model__min_samples_leaf,param_model__min_samples_split,param_model__splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.232582,0.017820,0.049032,0.007896,3,1,2,random,"{'model__max_depth': 3, 'model__min_samples_le...",0.975282,0.972466,0.975602,0.976853,0.975602,0.975161,0.001451,1
1,0.296006,0.018520,0.062955,0.008194,3,1,2,best,"{'model__max_depth': 3, 'model__min_samples_le...",0.975282,0.972466,0.975602,0.976853,0.975602,0.975161,0.001451,1
2,0.282989,0.015728,0.052907,0.007609,3,1,3,random,"{'model__max_depth': 3, 'model__min_samples_le...",0.975282,0.972466,0.975602,0.976853,0.975602,0.975161,0.001451,1
3,0.257531,0.007385,0.054799,0.007832,3,1,3,best,"{'model__max_depth': 3, 'model__min_samples_le...",0.975282,0.972466,0.975602,0.976853,0.975602,0.975161,0.001451,1
4,0.222445,0.009832,0.045015,0.004309,3,1,4,random,"{'model__max_depth': 3, 'model__min_samples_le...",0.975282,0.972466,0.975602,0.976853,0.975602,0.975161,0.001451,1

In [5]:
model = grid_report(grid, test_dataset, experiment)

2025/03/12 12:55:42 INFO mlflow.tracking.fluent: Experiment with name 'final' does not exist. Creating a new experiment.

{'model__max_depth': 3, 'model__min_samples_leaf': 1, 'model__min_samples_split': 2, 'model__splitter': 'random'}
              precision    recall  f1-score   support

           0     0.9853    0.9946    0.9899      5742
           1     0.9921    0.9786    0.9853      3974

    accuracy                         0.9881      9716
   macro avg     0.9887    0.9866    0.9876      9716
weighted avg     0.9881    0.9881    0.9880      9716

2025/03/12 12:55:47 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

In [6]:
analyze_variables(model, test_dataset, output_folder)
print_tree(model, test_dataset, output_folder)

In [7]:
output_folder = f"{case_folder}/complete"
grid, summary = cross_validation(
    [("model", DecisionTreeClassifier())],
    train_dataset,
    {
        "model__splitter": ["random", "best"],
        "model__max_depth": [35, 40, 45],
        "model__min_samples_split": [2, 3, 4],
        "model__min_samples_leaf": [1, 2, 3],
    },
    include_all=True,
)
summary

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__max_depth,param_model__min_samples_leaf,param_model__min_samples_split,param_model__splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
18,0.833991,0.014373,0.040216,0.001279,40,1,2,random,"{'model__max_depth': 40, 'model__min_samples_l...",0.908949,0.910826,0.911792,0.912418,0.916171,0.912031,0.002379,1
19,0.856642,0.005482,0.037884,0.001167,40,1,2,best,"{'model__max_depth': 40, 'model__min_samples_l...",0.908949,0.912703,0.909603,0.910854,0.917735,0.911969,0.003155,2
36,0.832566,0.009945,0.037928,0.000569,45,1,2,random,"{'model__max_depth': 45, 'model__min_samples_l...",0.912703,0.910826,0.909290,0.909290,0.917423,0.911906,0.003031,3
1,0.874040,0.023251,0.042013,0.005243,35,1,2,best,"{'model__max_depth': 35, 'model__min_samples_l...",0.907384,0.910826,0.910854,0.911480,0.917735,0.911656,0.003364,4
0,0.841951,0.019827,0.041212,0.003184,35,1,2,random,"{'model__max_depth': 35, 'model__min_samples_l...",0.911452,0.911139,0.910228,0.907413,0.917110,0.911468,0.003160,5

In [8]:
model = grid_report(grid, test_dataset, experiment)
save_model(model, model_path(output_folder))

{'model__max_depth': 40, 'model__min_samples_leaf': 1, 'model__min_samples_split': 2, 'model__splitter': 'random'}
              precision    recall  f1-score   support

           0     0.9426    0.9406    0.9416      5742
           1     0.9145    0.9172    0.9158      3974

    accuracy                         0.9310      9716
   macro avg     0.9285    0.9289    0.9287      9716
weighted avg     0.9311    0.9310    0.9311      9716

2025/03/12 12:56:42 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

In [9]:
analyze_variables(model, test_dataset, output_folder)
print_tree(model, test_dataset, output_folder)
check_bias(model, train_dataset, test_dataset, bias_prone_variables)

Sexo_MASCULINO | Statistical Parity Difference:  -0.2408345851066789
Sexo_MASCULINO | Equal Opportunity Difference:  -0.03906865650654401
Grupo Etario_Entre 18 y 40 años | Statistical Parity Difference:  -0.09138253958988296
Grupo Etario_Entre 18 y 40 años | Equal Opportunity Difference:  -0.02015297186045717
Grupo Etario_Entre 41 y 60 años | Statistical Parity Difference:  0.06025507690328158
Grupo Etario_Entre 41 y 60 años | Equal Opportunity Difference:  0.015420066538625377
Grupo Etario_Mayor de 60 años | Statistical Parity Difference:  0.13790560471976404
Grupo Etario_Mayor de 60 años | Equal Opportunity Difference:  0.03493340252551469

In [10]:
output_folder = f"{case_folder}/complete_unbiased"
model = train_unbiased_model(model, train_dataset, test_dataset, experiment)
save_model(model, model_path(output_folder))
analyze_variables(model, test_dataset, output_folder)
print_tree(model, test_dataset, output_folder)
check_bias(model, train_dataset, test_dataset, bias_prone_variables)

              precision    recall  f1-score   support

           0     0.9448    0.9368    0.9408      5742
           1     0.9098    0.9210    0.9153      3974

    accuracy                         0.9303      9716
   macro avg     0.9273    0.9289    0.9281      9716
weighted avg     0.9305    0.9303    0.9304      9716

2025/03/12 12:56:48 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

Sexo_MASCULINO | Statistical Parity Difference:  -0.24020556900052853
Sexo_MASCULINO | Equal Opportunity Difference:  -0.04700659818820796
Grupo Etario_Entre 18 y 40 años | Statistical Parity Difference:  -0.08937214906977325
Grupo Etario_Entre 18 y 40 años | Equal Opportunity Difference:  -0.021493894553570314
Grupo Etario_Entre 41 y 60 años | Statistical Parity Difference:  0.055859209972207335
Grupo Etario_Entre 41 y 60 años | Equal Opportunity Difference:  0.016256696895586842
Grupo Etario_Mayor de 60 años | Statistical Parity Difference:  0.15118089626606757
Grupo Etario_Mayor de 60 años | Equal Opportunity Difference:  0.03882546272271237

In [11]:
output_folder = f"{case_folder}/simple"
grid, summary = cross_validation(
    [("model", DecisionTreeClassifier())],
    train_dataset,
    {
        "model__splitter": ["random", "best"],
        "model__max_depth": [3, 5, 8],
        "model__min_samples_split": [2, 3, 4],
        "model__min_samples_leaf": [4, 5, 6],
    },
)
summary

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__max_depth,param_model__min_samples_leaf,param_model__min_samples_split,param_model__splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
24,0.087000,0.000894,0.013600,0.000489,5,5,2,random,"{'model__max_depth': 5, 'model__min_samples_le...",0.900188,0.883917,0.888958,0.898029,0.893025,0.892824,0.005927,1
25,0.087999,0.000632,0.014401,0.000490,5,5,2,best,"{'model__max_depth': 5, 'model__min_samples_le...",0.900188,0.883917,0.888958,0.898029,0.893025,0.892824,0.005927,1
26,0.087800,0.000980,0.014400,0.000799,5,5,3,random,"{'model__max_depth': 5, 'model__min_samples_le...",0.900188,0.883917,0.888958,0.898029,0.893025,0.892824,0.005927,1
27,0.085600,0.001018,0.013400,0.000489,5,5,3,best,"{'model__max_depth': 5, 'model__min_samples_le...",0.900188,0.883917,0.888958,0.898029,0.893025,0.892824,0.005927,1
28,0.086800,0.002228,0.014000,0.000632,5,5,4,random,"{'model__max_depth': 5, 'model__min_samples_le...",0.900188,0.883917,0.888958,0.898029,0.893025,0.892824,0.005927,1

In [12]:
model = grid_report(grid, test_dataset, experiment)
save_model(model, model_path(output_folder))

{'model__max_depth': 5, 'model__min_samples_leaf': 5, 'model__min_samples_split': 2, 'model__splitter': 'random'}
              precision    recall  f1-score   support

           0     0.9371    0.9711    0.9538      5742
           1     0.9559    0.9059    0.9302      3974

    accuracy                         0.9444      9716
   macro avg     0.9465    0.9385    0.9420      9716
weighted avg     0.9448    0.9444    0.9442      9716

2025/03/12 12:57:07 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

In [13]:
analyze_variables(model, test_dataset, output_folder)
print_tree(model, test_dataset, output_folder)
check_bias(model, train_dataset, test_dataset, bias_prone_variables)

Sexo_MASCULINO | Statistical Parity Difference:  -0.22626742051239257
Sexo_MASCULINO | Equal Opportunity Difference:  -0.015254831461551932
Grupo Etario_Entre 18 y 40 años | Statistical Parity Difference:  -0.07165289325116542
Grupo Etario_Entre 18 y 40 años | Equal Opportunity Difference:  -0.001218435851067845
Grupo Etario_Entre 41 y 60 años | Statistical Parity Difference:  0.037375186795234216
Grupo Etario_Entre 41 y 60 años | Equal Opportunity Difference:  -0.0036980994673305734
Grupo Etario_Mayor de 60 años | Statistical Parity Difference:  0.1605644458709707
Grupo Etario_Mayor de 60 años | Equal Opportunity Difference:  0.04044282996021442

In [14]:
output_folder = f"{case_folder}/simple_unbiased"
model = train_unbiased_model(model, train_dataset, test_dataset, experiment)
save_model(model, model_path(output_folder))
analyze_variables(model, test_dataset, output_folder)
print_tree(model, test_dataset, output_folder)
check_bias(model, train_dataset, test_dataset, bias_prone_variables)

              precision    recall  f1-score   support

           0     0.9371    0.9711    0.9538      5742
           1     0.9559    0.9059    0.9302      3974

    accuracy                         0.9444      9716
   macro avg     0.9465    0.9385    0.9420      9716
weighted avg     0.9448    0.9444    0.9442      9716

2025/03/12 12:57:11 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

Sexo_MASCULINO | Statistical Parity Difference:  -0.22626742051239257
Sexo_MASCULINO | Equal Opportunity Difference:  -0.015254831461551932
Grupo Etario_Entre 18 y 40 años | Statistical Parity Difference:  -0.07165289325116542
Grupo Etario_Entre 18 y 40 años | Equal Opportunity Difference:  -0.001218435851067845
Grupo Etario_Entre 41 y 60 años | Statistical Parity Difference:  0.037375186795234216
Grupo Etario_Entre 41 y 60 años | Equal Opportunity Difference:  -0.0036980994673305734
Grupo Etario_Mayor de 60 años | Statistical Parity Difference:  0.1605644458709707
Grupo Etario_Mayor de 60 años | Equal Opportunity Difference:  0.04044282996021442

In [15]:
test_report_umbral(model, test_dataset, 0.4, experiment)
test_report_umbral(model, test_dataset, 0.25, experiment)
test_report_umbral(model, test_dataset, 0.1, experiment)

              precision    recall  f1-score   support

           0     0.9371    0.9711    0.9538      5742
           1     0.9559    0.9059    0.9302      3974

    accuracy                         0.9444      9716
   macro avg     0.9465    0.9385    0.9420      9716
weighted avg     0.9448    0.9444    0.9442      9716

2025/03/12 12:57:16 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

              precision    recall  f1-score   support

           0     0.9590    0.8802    0.9179      5742
           1     0.8453    0.9456    0.8926      3974

    accuracy                         0.9070      9716
   macro avg     0.9021    0.9129    0.9053      9716
weighted avg     0.9125    0.9070    0.9076      9716

2025/03/12 12:57:19 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

              precision    recall  f1-score   support

           0     0.9817    0.7929    0.8773      5742
           1     0.7659    0.9786    0.8593      3974

    accuracy                         0.8689      9716
   macro avg     0.8738    0.8858    0.8683      9716
weighted avg     0.8934    0.8689    0.8699      9716

2025/03/12 12:57:22 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.