In [3]:
%pip install ../model --q

Note: you may need to restart the kernel to use updated packages.

In [4]:
from sklearn.tree import DecisionTreeClassifier
from model.analyze import analyze_variables, check_bias, print_tree
from model.train import (
    cross_validation,
    grid_report,
    load_data,
    random_seed,
    test_report_umbral,
    train_unbiased_model,
)
from model.model import save_model
import random

random.seed(random_seed)

WARNING:root:No module named 'tensorflow': AdversarialDebiasing will be unavailable. To install, run:
pip install 'aif360[AdversarialDebiasing]'
WARNING:root:No module named 'tensorflow': AdversarialDebiasing will be unavailable. To install, run:
pip install 'aif360[AdversarialDebiasing]'
WARNING:root:No module named 'fairlearn': ExponentiatedGradientReduction will be unavailable. To install, run:
pip install 'aif360[Reductions]'
WARNING:root:No module named 'fairlearn': GridSearchReduction will be unavailable. To install, run:
pip install 'aif360[Reductions]'
WARNING:root:No module named 'inFairness': SenSeI and SenSR will be unavailable. To install, run:
pip install 'aif360[inFairness]'
WARNING:root:No module named 'fairlearn': GridSearchReduction will be unavailable. To install, run:
pip install 'aif360[Reductions]'

In [5]:
train_dataset, test_dataset = load_data("../data/raw_data.csv")
bias_prone_variables = ["Sexo", "Grupo Etario"]
experiment = "final"
case_folder = f"./reports/{experiment}"


def model_path(output_folder: str):
    return f"{output_folder}/model"

In [6]:
output_folder = f"{case_folder}/biased"
grid, summary = cross_validation(
    [("model", DecisionTreeClassifier())],
    train_dataset,
    {
        "model__splitter": ["random", "best"],
        "model__max_depth": [3, 5, 7],
        "model__min_samples_split": [2, 3, 4],
        "model__min_samples_leaf": [1, 2, 3],
    },
    include_all=True,
    include_bias=True,
)
summary

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__max_depth,param_model__min_samples_leaf,param_model__min_samples_split,param_model__splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.222343,0.003783,0.051820,0.007947,3,1,2,random,"{'model__max_depth': 3, 'model__min_samples_le...",0.975282,0.972466,0.975602,0.976853,0.975602,0.975161,0.001451,1
1,0.289890,0.007750,0.062149,0.005750,3,1,2,best,"{'model__max_depth': 3, 'model__min_samples_le...",0.975282,0.972466,0.975602,0.976853,0.975602,0.975161,0.001451,1
2,0.247823,0.011187,0.053009,0.008423,3,1,3,random,"{'model__max_depth': 3, 'model__min_samples_le...",0.975282,0.972466,0.975602,0.976853,0.975602,0.975161,0.001451,1
3,0.245521,0.011040,0.042911,0.002056,3,1,3,best,"{'model__max_depth': 3, 'model__min_samples_le...",0.975282,0.972466,0.975602,0.976853,0.975602,0.975161,0.001451,1
4,0.224776,0.005459,0.043719,0.001619,3,1,4,random,"{'model__max_depth': 3, 'model__min_samples_le...",0.975282,0.972466,0.975602,0.976853,0.975602,0.975161,0.001451,1

In [7]:
model = grid_report(grid, test_dataset, experiment)

2025/03/05 18:15:08 INFO mlflow.tracking.fluent: Experiment with name 'final' does not exist. Creating a new experiment.

{'model__max_depth': 3, 'model__min_samples_leaf': 1, 'model__min_samples_split': 2, 'model__splitter': 'random'}
              precision    recall  f1-score   support

           0     0.9853    0.9946    0.9899      5742
           1     0.9921    0.9786    0.9853      3974

    accuracy                         0.9881      9716
   macro avg     0.9887    0.9866    0.9876      9716
weighted avg     0.9881    0.9881    0.9880      9716

2025/03/05 18:15:16 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

In [8]:
analyze_variables(model, test_dataset, output_folder)
print_tree(model, test_dataset, output_folder)

In [9]:
output_folder = f"{case_folder}/complete"
grid, summary = cross_validation(
    [("model", DecisionTreeClassifier())],
    train_dataset,
    {
        "model__splitter": ["random", "best"],
        "model__max_depth": [30, 35, 40],
        "model__min_samples_split": [2, 3, 4],
        "model__min_samples_leaf": [1, 2, 3],
    },
    include_all=True,
)
summary

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__max_depth,param_model__min_samples_leaf,param_model__min_samples_split,param_model__splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
1,0.887875,0.018176,0.040845,0.001931,30,1,2,best,"{'model__max_depth': 30, 'model__min_samples_l...",0.909574,0.914268,0.911480,0.909916,0.918361,0.912720,0.003272,1
19,0.939456,0.017800,0.043011,0.002687,35,1,2,best,"{'model__max_depth': 35, 'model__min_samples_l...",0.908949,0.912078,0.909916,0.908977,0.918361,0.911656,0.003540,2
37,0.905439,0.011008,0.040406,0.001321,40,1,2,best,"{'model__max_depth': 40, 'model__min_samples_l...",0.908949,0.911765,0.909603,0.912105,0.915546,0.911593,0.002318,3
33,0.790750,0.034631,0.043205,0.005594,35,3,3,best,"{'model__max_depth': 35, 'model__min_samples_l...",0.911452,0.905507,0.917110,0.912105,0.911167,0.911468,0.003684,4
51,0.807764,0.014259,0.039296,0.000600,40,3,3,best,"{'model__max_depth': 40, 'model__min_samples_l...",0.910826,0.905820,0.916484,0.912105,0.911480,0.911343,0.003400,5

In [10]:
model = grid_report(grid, test_dataset, experiment)
save_model(model, model_path(output_folder))

{'model__max_depth': 30, 'model__min_samples_leaf': 1, 'model__min_samples_split': 2, 'model__splitter': 'best'}
              precision    recall  f1-score   support

           0     0.9409    0.9343    0.9376      5742
           1     0.9061    0.9152    0.9106      3974

    accuracy                         0.9265      9716
   macro avg     0.9235    0.9248    0.9241      9716
weighted avg     0.9267    0.9265    0.9266      9716

2025/03/05 18:16:15 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

In [11]:
analyze_variables(model, test_dataset, output_folder)
print_tree(model, test_dataset, output_folder)
check_bias(model, train_dataset, test_dataset, bias_prone_variables)

Sexo_MASCULINO | Statistical Parity Difference:  -0.22899072296865003
Sexo_MASCULINO | Equal Opportunity Difference:  -0.025262946149136378
Grupo Etario_Entre 18 y 40 años | Statistical Parity Difference:  -0.09029912356046266
Grupo Etario_Entre 18 y 40 años | Equal Opportunity Difference:  -0.011697895450913709
Grupo Etario_Entre 41 y 60 años | Statistical Parity Difference:  0.05822710748790888
Grupo Etario_Entre 41 y 60 años | Equal Opportunity Difference:  0.007430938815234267
Grupo Etario_Mayor de 60 años | Statistical Parity Difference:  0.14324839133690986
Grupo Etario_Mayor de 60 años | Equal Opportunity Difference:  0.03285763708700917

In [12]:
output_folder = f"{case_folder}/complete_unbiased"
model = train_unbiased_model(model, train_dataset, test_dataset, experiment)
save_model(model, model_path(output_folder))
analyze_variables(model, test_dataset, output_folder)
print_tree(model, test_dataset, output_folder)
check_bias(model, train_dataset, test_dataset, bias_prone_variables)

              precision    recall  f1-score   support

           0     0.9409    0.9343    0.9376      5742
           1     0.9061    0.9152    0.9106      3974

    accuracy                         0.9265      9716
   macro avg     0.9235    0.9248    0.9241      9716
weighted avg     0.9267    0.9265    0.9266      9716

2025/03/05 18:16:21 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

Sexo_MASCULINO | Statistical Parity Difference:  -0.2325993073520821
Sexo_MASCULINO | Equal Opportunity Difference:  -0.01885419830109103
Grupo Etario_Entre 18 y 40 años | Statistical Parity Difference:  -0.08366119899597224
Grupo Etario_Entre 18 y 40 años | Equal Opportunity Difference:  -0.00859444874622517
Grupo Etario_Entre 41 y 60 años | Statistical Parity Difference:  0.05382337289150502
Grupo Etario_Entre 41 y 60 años | Equal Opportunity Difference:  0.004249758322748098
Grupo Etario_Mayor de 60 años | Statistical Parity Difference:  0.13337383648952267
Grupo Etario_Mayor de 60 años | Equal Opportunity Difference:  0.034154990486075065

In [13]:
output_folder = f"{case_folder}/simple"
grid, summary = cross_validation(
    [("model", DecisionTreeClassifier())],
    train_dataset,
    {
        "model__splitter": ["random", "best"],
        "model__max_depth": [5, 8, 11],
        "model__min_samples_split": [2, 3, 4],
        "model__min_samples_leaf": [4, 5, 6],
    },
)
summary

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__max_depth,param_model__min_samples_leaf,param_model__min_samples_split,param_model__splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
6,0.095430,0.005027,0.014409,0.000502,5,5,2,random,"{'model__max_depth': 5, 'model__min_samples_le...",0.900188,0.883917,0.888958,0.898029,0.893025,0.892824,0.005927,1
7,0.090084,0.001851,0.014422,0.000485,5,5,2,best,"{'model__max_depth': 5, 'model__min_samples_le...",0.900188,0.883917,0.888958,0.898029,0.893025,0.892824,0.005927,1
13,0.088557,0.002195,0.013874,0.000558,5,6,2,best,"{'model__max_depth': 5, 'model__min_samples_le...",0.900188,0.883917,0.888958,0.898029,0.893025,0.892824,0.005927,1
12,0.091613,0.002256,0.014460,0.000832,5,6,2,random,"{'model__max_depth': 5, 'model__min_samples_le...",0.900188,0.883917,0.888958,0.898029,0.893025,0.892824,0.005927,1
11,0.091597,0.004666,0.014572,0.000422,5,5,4,best,"{'model__max_depth': 5, 'model__min_samples_le...",0.900188,0.883917,0.888958,0.898029,0.893025,0.892824,0.005927,1

In [14]:
model = grid_report(grid, test_dataset, experiment)
save_model(model, model_path(output_folder))

{'model__max_depth': 5, 'model__min_samples_leaf': 5, 'model__min_samples_split': 2, 'model__splitter': 'random'}
              precision    recall  f1-score   support

           0     0.9371    0.9711    0.9538      5742
           1     0.9559    0.9059    0.9302      3974

    accuracy                         0.9444      9716
   macro avg     0.9465    0.9385    0.9420      9716
weighted avg     0.9448    0.9444    0.9442      9716

2025/03/05 18:16:40 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

In [15]:
analyze_variables(model, test_dataset, output_folder)
print_tree(model, test_dataset, output_folder)
check_bias(model, train_dataset, test_dataset, bias_prone_variables)

Sexo_MASCULINO | Statistical Parity Difference:  -0.22626742051239257
Sexo_MASCULINO | Equal Opportunity Difference:  -0.015254831461551932
Grupo Etario_Entre 18 y 40 años | Statistical Parity Difference:  -0.07165289325116542
Grupo Etario_Entre 18 y 40 años | Equal Opportunity Difference:  -0.001218435851067845
Grupo Etario_Entre 41 y 60 años | Statistical Parity Difference:  0.037375186795234216
Grupo Etario_Entre 41 y 60 años | Equal Opportunity Difference:  -0.0036980994673305734
Grupo Etario_Mayor de 60 años | Statistical Parity Difference:  0.1605644458709707
Grupo Etario_Mayor de 60 años | Equal Opportunity Difference:  0.04044282996021442

In [16]:
output_folder = f"{case_folder}/simple_unbiased"
model = train_unbiased_model(model, train_dataset, test_dataset, experiment)
save_model(model, model_path(output_folder))
analyze_variables(model, test_dataset, output_folder)
print_tree(model, test_dataset, output_folder)
check_bias(model, train_dataset, test_dataset, bias_prone_variables)

              precision    recall  f1-score   support

           0     0.9371    0.9711    0.9538      5742
           1     0.9559    0.9059    0.9302      3974

    accuracy                         0.9444      9716
   macro avg     0.9465    0.9385    0.9420      9716
weighted avg     0.9448    0.9444    0.9442      9716

2025/03/05 18:16:45 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

Sexo_MASCULINO | Statistical Parity Difference:  -0.22626742051239257
Sexo_MASCULINO | Equal Opportunity Difference:  -0.015254831461551932
Grupo Etario_Entre 18 y 40 años | Statistical Parity Difference:  -0.07165289325116542
Grupo Etario_Entre 18 y 40 años | Equal Opportunity Difference:  -0.001218435851067845
Grupo Etario_Entre 41 y 60 años | Statistical Parity Difference:  0.037375186795234216
Grupo Etario_Entre 41 y 60 años | Equal Opportunity Difference:  -0.0036980994673305734
Grupo Etario_Mayor de 60 años | Statistical Parity Difference:  0.1605644458709707
Grupo Etario_Mayor de 60 años | Equal Opportunity Difference:  0.04044282996021442

In [17]:
test_report_umbral(model, test_dataset, 0.4, experiment)
test_report_umbral(model, test_dataset, 0.25, experiment)
test_report_umbral(model, test_dataset, 0.1, experiment)

              precision    recall  f1-score   support

           0     0.9371    0.9711    0.9538      5742
           1     0.9559    0.9059    0.9302      3974

    accuracy                         0.9444      9716
   macro avg     0.9465    0.9385    0.9420      9716
weighted avg     0.9448    0.9444    0.9442      9716

2025/03/05 18:16:49 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

              precision    recall  f1-score   support

           0     0.9590    0.8802    0.9179      5742
           1     0.8453    0.9456    0.8926      3974

    accuracy                         0.9070      9716
   macro avg     0.9021    0.9129    0.9053      9716
weighted avg     0.9125    0.9070    0.9076      9716

2025/03/05 18:16:53 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

              precision    recall  f1-score   support

           0     0.9817    0.7929    0.8773      5742
           1     0.7659    0.9786    0.8593      3974

    accuracy                         0.8689      9716
   macro avg     0.8738    0.8858    0.8683      9716
weighted avg     0.8934    0.8689    0.8699      9716

2025/03/05 18:16:57 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.